[package]
name = "generate"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
boilerplate.workspace = true
camino.workspace = true
filepack = { path = "../.." }

[lints]
workspace = true
