[book]
title = "Filepack"
authors = ["Casey Rodarmor"]
description = "content-addressed packages"
language = "en"

[build]
build-dir = "build"
create-missing = false

[output.html]
git-repository-url = "https://github.com/casey/filepack"

[output.linkcheck2]
follow-web-links = false
require-md-extension = true
warning-policy = "error"
